language: java

git:
  depth: 5

branches:
 only:
  - master
  - development

sudo: true

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - fakeroot
            - oracle-java8-installer
    - os: osx
      osx_image: xcode9.3beta


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - chmod +x gradlew

install: true

script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew clean build; else ./gradlew --debug clean build bintrayUpload; fi

cache:
  directories:
    - $HOME/.gradle/
