language: java

git:
  depth: 5

branches:
 only:
  - master
  - development

sudo: true

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - fakeroot
    - os: osx
      osx_image: xcode9.2


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); else chmod +x travis.sh; ./travis.sh; export JAVA_HOME=~/jvm/jdk1.8.0_162; fi;
  - chmod +x gradlew

install: true

script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew clean build -x :slideshowfx-icons:test; else ./gradlew clean build -x :slideshowfx-icons:test; fi

cache:
  directories:
    - $HOME/.gradle
    - $HOME/jvm
