language: java

git:
  depth: 5

branches:
 only:
  - master

sudo: true

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); fi

install: true

script:
  - chmod +x ./gradlew
  - ./gradlew build bintrayUpload -x test
  - ./gradlew --stop

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/