version: 1.0.{build}

environment:
  MAVEN_VERSION: 3.5.2
  MAVEN_INSTALLATIONS_ROOT_DIR: C:\maven
  M2_HOME: $MAVEN_INSTALLATIONS_ROOT_DIR\apache-maven-$MAVEN_VERSION

branches:
  only:
    - master
    - development

cache:
  - '%USERPROFILE%\.m2'
  - '%M2_HOME% -> appveyor.yml'

skip_tags: false

skip_non_tags: false

image: Visual Studio 2017

clone_depth: 5

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
        if (!(Test-Path -Path "$env:M2_HOME" )) {
          Write-Host "Downloading Maven $env:MAVEN_VERSION"
          (new-object System.Net.WebClient).DownloadFile("https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$env:MAVEN_VERSION/apache-maven-$env:MAVEN_VERSION-bin.zip", '$env:MAVEN_INSTALLATIONS_ROOT_DIR\maven-bin.zip')
          [System.IO.Compression.ZipFile]::ExtractToDirectory("$env:MAVEN_INSTALLATIONS_ROOT_DIR\maven-bin.zip", "$env:MAVEN_INSTALLATIONS_ROOT_DIR")
        }

platform:
  - x86
  - x64

before_build:
  - IF "%PLATFORM%" == "x86" (SET JAVA_HOME="C:\Program Files (x86)\Java\jdk1.8.0")
  - IF "%PLATFORM%" == "x64" (SET JAVA_HOME="C:\Program Files\Java\jdk1.8.0")
  - SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH%
  - java -version
  - mvn -version

build_script:
  - IF "%APPVEYOR_REPO_BRANCH%" == "master" (mvn clean deploy)
  - IF NOT "%APPVEYOR_REPO_BRANCH%" == "master" (mvn clean install)