version: 2.0.{build}

branches:
  only:
    - master
    - development

cache:
  - '%USERPROFILE%\.gradle'

skip_tags: false

skip_non_tags: false

image: Visual Studio 2017

clone_depth: 5

environment:
  - _JAVA_OPTIONS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k"

platform:
  - x86
  - x64

before_build:
  - IF "%PLATFORM%" == "x86" (SET JAVA_HOME=C:\Progra~2\Java\jdk1.8.0)
  - IF "%PLATFORM%" == "x64" (SET JAVA_HOME=C:\Progra~1\Java\jdk1.8.0)
  - ECHO %JAVA_HOME%

build_script:
  - cmd: IF "%APPVEYOR_REPO_TAG_NAME%" == "" (gradlew clean build)
  - cmd: IF NOT "%APPVEYOR_REPO_TAG_NAME%" == "" (gradlew clean build bintrayUpload)
