version: 2.0.{build}

branches:
  only:
    - master
    - development

cache:
  - '%USERPROFILE%\.gradle'

skip_tags: false

skip_non_tags: false

image: Visual Studio 2017

clone_depth: 5

platform:
  - x86
  - x64

before_build:
  - IF "%PLATFORM%" == "x86" (SET JAVA_HOME=C:\Progra~2\Java\jdk1.8.0)
  - IF "%PLATFORM%" == "x64" (SET JAVA_HOME=C:\Progra~1\Java\jdk1.8.0)
  - ECHO %JAVA_HOME%

build_script:
  - cmd: IF "%APPVEYOR_REPO_BRANCH%" == "master" (gradlew clean build bintrayUpload)
  - cmd: IF NOT "%APPVEYOR_REPO_BRANCH%" == "master" (gradlew clean build)
