version: 1.0.{build}

branches:
  only:
    - master
    - development

cache:
  - '%USERPROFILE%\.m2'
  - '%M2_HOME% -> appveyor.yml'

skip_tags: false

skip_non_tags: false

image: Visual Studio 2017

clone_depth: 5

platform:
  - x86
  - x64

before_build:
  - IF "%PLATFORM%" == "x86" (SET JAVA_HOME="C:\Program Files (x86)\Java\jdk1.8.0")
  - IF "%PLATFORM%" == "x64" (SET JAVA_HOME="C:\Program Files\Java\jdk1.8.0")
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - java -version
  - mvn -version

build_script:
  - IF "%APPVEYOR_REPO_BRANCH%" == "master" (mvn clean deploy)
  - IF NOT "%APPVEYOR_REPO_BRANCH%" == "master" (mvn clean install)